### ISSUE TITLE
RobotpkgArchitectureReleaseCandidate missing in build files

### ISSUE THREAD

**Issue by NoelieRamuzat** [olivier-stasse/robotpkg_helpers#5]
You've changed the `arch_release_candidate` variable which was a json dictionary into a `RobotpkgArchitectureReleaseCandidate object` but have not change it in the python build files. So when the functions of `testing_deployment.py ` are called the `arch_release_candidate` is initialized as None and it is breaking (because looking for `arch_release_candidate.data  `which doesn't exist).

To fix it I have added in `rpkgh_rc_other_path`:
`from robotpkg_helpers import RobotpkgTests, build_test_rc_robotpkg_vars, RobotpkgArchitectureReleaseCandidate
arch_release_candidates=RobotpkgArchitectureReleaseCandidate('arch_test_rc.json')`

and modified:
`if arpgtestrc.perform_test_rc(dist_files_path=dist_files_path, arch_release_candidates=arch_release_candidates):`

In the `build_talos_dev/simulation` files it should be reasonable to do the same and initialize the `arch_release_candidates` variable with a `RobotpkgArchitectureReleaseCandidate object ` without any json file. (`arch_release_candidates = RobotpkgArchitectureReleaseCandidate()`)

**Comment by olivier-stasse** [comment]
You are right they are some files which are incompatibles with the new architecture.
I should have remove thems.
Normally commit 91f972a160a1bb5bfadb54873b98d7cb0f0c2778 is fixing the matter.

With respect to the solution you are suggesting, I am proposing to have json files specific to talos_dev and talos_simulation instead of python script.

You can then have an alias if you want a command without argument. 
What do you think ?

**Comment by NoelieRamuzat** [comment]
Thanks for the modifications, the commit [91f972a](https://github.com/olivier-stasse/robotpkg_helpers/commit/91f972a160a1bb5bfadb54873b98d7cb0f0c2778) fixes the issue.

Yes I think json files allow a clearer representation of the robotpkg architecture to be installed, thank you.
